USE [master]
GO

/****** Object:  Database [PagosDB]    Script Date: 11/09/2019 11:54:49 p. m. ******/
CREATE DATABASE [PagosDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PagosDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\PagosDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PagosDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\PagosDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [PagosDB] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PagosDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [PagosDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [PagosDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [PagosDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [PagosDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [PagosDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [PagosDB] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [PagosDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PagosDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PagosDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PagosDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [PagosDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [PagosDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PagosDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [PagosDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PagosDB] SET  ENABLE_BROKER 
GO

ALTER DATABASE [PagosDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PagosDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [PagosDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [PagosDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [PagosDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PagosDB] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [PagosDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [PagosDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [PagosDB] SET  MULTI_USER 
GO

ALTER DATABASE [PagosDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [PagosDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [PagosDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [PagosDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [PagosDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [PagosDB] SET QUERY_STORE = OFF
GO

USE [PagosDB]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [PagosDB] SET  READ_WRITE 
GO


